name: ci

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  streamloom:
    name: streamloom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - run: go fmt ./...

      - run: go vet ./...

      - run: go fix ./...

      - name: Ensure no changes after formatting and fixing
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "There are uncommitted changes after formatting/fixing. Please commit them before pushing.";
            git --no-pager diff;
            exit 1;
          fi

      - run: go build -ldflags "-X main.Version=test" -v .

      - run: go test -v ./...
