name: publish

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  latest:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - run: ko build --base-import-paths --tags=latest
        env:
          VERSION: ${{ github.sha }}
