name: publish

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  latest:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - run: ko build --base-import-paths --tags=latest
        env:
          VERSION: ${{ github.sha }}
